return {
    SPAWN_SCALE_MULTIPLIER = 1.25,

    BASE_SCALE_TWEEN_DURATION = 0.3,
    BASE_MERGE_SPEED = 400,
    BASE_MERGE_RANGE = 150,

    WEIGHT_DURATION_DIVISOR = 100,
    TIER_SCALING_DIVISOR = 10,

    MAX_TIER = math.huge,
    MIN_TIER = 1,

    ELASTICITY = 0.7,
    FRICTION = 0.98
}
